package mx.fei.dataaccess;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DatabaseConnectionManager {
    private static final Logger logger = Logger.getLogger(DatabaseConnectionManager.class.getName());
    private  static DatabaseConnectionManager connSingleton;
    private Connection connection;
    private String driver;
    private String url;
    private String username;
    private String password;

    private DatabaseConnectionManager() throws SQLException {
        loadProperties();
        try {
            Class.forName(driver);
        } catch (ClassNotFoundException e) {
            logger.log(Level.SEVERE,"No se encontro el driver JDBC" + driver,e);
        }
        connect();
    }

    private void loadProperties() throws SQLException {
        Properties properties = new Properties();
        try (InputStream input = getClass().getClassLoader().getResourceAsStream("db.properties")) {
            if (input == null) {
                throw new SQLException("Archivo db.properties no encontrado");
            }
            properties.load(input);
            driver = properties.getProperty("db.driver");
            username = properties.getProperty("db.username");
            password = properties.getProperty("db.password");
            String host = properties.getProperty("db.host");
            String port = properties.getProperty("db.port");
            String dataBase = properties.getProperty("db.name");

            url = "jdbc:mysql://" + host + ":" + port + "/" + dataBase + "?useTimezone=true&serverTimezone=UTC";

        } catch (IOException e) {
            logger.log(Level.SEVERE, "Error al leer db.properties", e);
        }
    }

    private void connect() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(url,username,password);
            logger.log(Level.INFO,"Conexion establecida con la base de datos");
        }
    }

    public void close() throws SQLException {
        if (connection != null) {
            connection.close();
            logger.log(Level.INFO,"Conexion cerrada");
        }
    }

    public PreparedStatement preparedStatement(String query) throws SQLException {
        connect();
        return connection.prepareStatement(query);
    }

    public PreparedStatement preparedStatement(String query,int autoGeneratedKeys) throws SQLException {
        connect();
        return connection.prepareStatement(query,autoGeneratedKeys);
    }

    public static DatabaseConnectionManager buildConnection() throws SQLException {
        if (connSingleton == null) {
            connSingleton = new DatabaseConnectionManager();
        }
        connSingleton.connect();
        return connSingleton;
    }
}